apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenkai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenkai-frontend
  template:
    metadata:
      labels:
        app: tenkai-frontend
    spec:
      containers:
      - name: tenkai-frontend
        image: 628263975501.dkr.ecr.us-east-1.amazonaws.com/tenkai-frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://tenkai-api-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: tenkai-frontend-service
spec:
  selector:
    app: tenkai-frontend
  ports:
  - port: 80
    targetPort: 8501
  type: LoadBalancer